name: Python Bot

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard Linux environment

    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Sets up the Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Installs the required libraries from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. A simple test to see if the bot script runs without crashing on import
      # It won't actually start the bot, but it validates the setup.
      - name: Run a dry-run test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py
